### ISSUE TITLE
Plugin cast ERROR message on QGIS start ( 3.34.1-Prizren)

### ISSUE THREAD

**Issue by GISAabenraa** [yuzisheng/quick-copy#2]
2024-07-02T09:56:48     WARNING    Python error : 
`An error has occurred while executing Python code: See message log (Python Error) for more details.`

2024-07-02T09:55:08     WARNING    Traceback (most recent call last):
```
File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick-copy\copy_tool.py", line 32, in change_layer
              if self.vector_layer:
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
```
             
2024-07-02T09:55:15     WARNING    Traceback (most recent call last):
```
File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick-copy\copy_tool.py", line 32, in change_layer
              if self.vector_layer:
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
```

**Comment by GISAabenraa** [comment]
An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted 
Traceback (most recent call last):
  File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick-copy\copy_tool.py", line 32, in change_layer
    if self.vector_layer:
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.34.1-Prizren Prizren, 133927424d 

Python Path:
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.1\apps\grass\grass83\etc\python
C:\Users\username\Documents
C:\Program Files\QGIS 3.34.1\bin\python39.zip
C:\PROGRA~1\QGIS33~1.1\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib
C:\Program Files\QGIS 3.34.1\bin
C:\Users\username\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.1\apps\Python39
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\deepness\python3.9
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
..
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\landxml2qgis
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\landxml2qgis\wheels\visvalingamwyatt-0.1.4-py2.py3-none-any.whl
.
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs

**Comment by eisenchow** [comment]
> 2024-07-02T09:56:48 WARNING Python error : `An error has occurred while executing Python code: See message log (Python Error) for more details.`
> 
> 2024-07-02T09:55:08 WARNING Traceback (most recent call last):
> 
> ```
> File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick-copy\copy_tool.py", line 32, in change_layer
>               if self.vector_layer:
>              RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
> ```
> 
> 2024-07-02T09:55:15 WARNING Traceback (most recent call last):
> 
> ```
> File "C:\Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick-copy\copy_tool.py", line 32, in change_layer
>               if self.vector_layer:
>              RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
> ```

Thank for using QuickCopy!
I am unable to reproduce this error. Can you please attach a simple project that reproduces this?
